crossbario/autobahn-cpp

- autobahn/autobahn.hpp
- autobahn/autobahn_impl.hpp
The only change is the inclusion of a two-way handshake between the client and
the server as soon as the socket connection is opened. This handshake
establishes the serialization format the client wishes to use, and sets some
maximum message sizes.
This addresses https://github.com/tavendo/AutobahnCpp/issues/15
> Implement the updated WAMP-over-RawSocket spec.

- autobahn/autobahn_impl.hpp
The DOUBLE type has been deprecated; see
https://github.com/msgpack/msgpack-c/wiki/cpp_configure
This addresses https://github.com/tavendo/AutobahnCpp/issues/30
> Use msgpack::type::FLOAT instead of msgpack::type::DOUBLE.

- autobahn/wamp_transport.hpp
- autobahn/wamp_transport_handler.hpp
@oberstet Here are the interfaces that we discussed. Need to further understand the intent of how the on_attach and on_detach are supposed to work.
My main concern right now is that the session is not in a state where it could be reused due to all of the promises, and internal state that would need to be properly dealt with. I am considering actually leaving out the `on_attach` and `on_detach` pieces for the time being and still just pass the transport into the session constructor. An incremental step from there would be to remove the transport from the session constructor and add in the attach and detach semantics.
I would say that I am about 90% complete the first iteration that doesn't include the `on_attach` and `on_detach` methods in the handler.
> Interfaces for discussion about transport abstraction.

- autobahn/wamp_transport.hpp
As per our conversation on #54 I have updated the interfaces. Not if you still want to go with the `wamp_transport_handler` so I left that part of the interface intact and did not incorporate 'wamp_transport::on_message` or the `message_handler`.
> Interface refinements for transports.

- autobahn/wamp_auth_utils.hpp
- autobahn/wamp_session.ipp
Build was failing for me due to complaints about unused variables.
> Fix unused variables error in build

- autobahn/wamp_session.ipp
When a call result is processed we need to cleanup the
pending call result.
> Fix leak in call processing

- autobahn/wamp_session.ipp
When a procedure is registered with the router we need to
to cleanup the pending registration request when the
registered message is processed.
> Fix leak in registering procedures

- examples/subscriber.cpp
The publish example was not working correctly because
the the subscriber was trying to receive the event
argument as an integer instead of a as a string.
Resolves: #64 #80
> Fix invalid type conversion in publish example

- autobahn/exceptions.hpp
- autobahn/wamp_session.hpp
- autobahn/wamp_session.ipp
I did not have the total overview of how to handle the "details dict" along with an abort ( is it always string -> string mapping ?? ). 
So with those changes here, I took the very conservative road - only adding the URI to the exception raised.
> add process_abort function

- CMakeLists.txt
Looks like these files were not previously added to CMakeLists.txt which was causing build failures for 3rd-party projects.
> Add missing subscribe options files to cmake

- autobahn/wamp_subscribe_options.ipp
The subscribe options dictionary should always be specified even if
the dictionary is empty.
Related: #98
> Fix subscribe options

- CMakeLists.txt
- autobahn/wamp_message.hpp
- autobahn/wamp_message.ipp
- autobahn/wamp_message_type.ipp
- autobahn/wamp_rawsocket_transport.ipp
- examples/callee.cpp
- examples/caller.cpp
- examples/publisher.cpp
- examples/subscriber.cpp
- examples/uds.cpp
- examples/wampcra.cpp
This commit cleans up debugging in the examples to correctly honor the
debug parameter and adds additional debugging for dumping messages
when sending and receiving.
Related: #98
> Improve debugging

- autobahn/wamp_session.hpp
- autobahn/wamp_session.ipp
As per spec draft, `WELCOME` message contains a dictionary with values describing router features as well as router assigned (reassigned) authid and role.  
This is a non-breaking change, that doesn't require changing existing code. Welcome dictionary is accessible via `wamp_session::welcome_details()` 
The alternative approach would be changing the signature of join future to something like:
```
// Future to be fired when session was joined.
boost::promise<welcome_message> m_session_join;
```
> Save WELCOME message Details dictionary

- autobahn/wamp_event.ipp
- autobahn/wamp_invocation.ipp
- autobahn/wamp_session.ipp
Prevent copy elision warnings [-Wpessimizing-move] by removing redundant std::move calls 
Also fix warning about obsolete ATOMIC_VAR_INIT, use regular std::atomic constructor
> Fix warnings/errors on latest clang/Xcode 7.3

- autobahn/boost_config.hpp
- autobahn/wamp_call.hpp
- autobahn/wamp_rawsocket_transport.hpp
- autobahn/wamp_register_request.hpp
- autobahn/wamp_session.hpp
- autobahn/wamp_subscribe_request.hpp
- autobahn/wamp_tcp_transport.hpp
- autobahn/wamp_transport.hpp
- autobahn/wamp_transport_handler.hpp
- autobahn/wamp_unsubscribe_request.hpp
- autobahn/wamp_websocket_transport.hpp
- autobahn/wamp_websocketpp_websocket_transport.hpp
This consolidates the boost future macros into one place and prevents warnings on windows using ifdefs.
> refactor boost future macros into common header with ifdefs

- autobahn/wamp_session.hpp
Removes erroneous qualifier from wamp_session::unprovide.
> Remove uneeded qualifier from wamp_session::unprovide

- autobahn/wamp_rawsocket_transport.ipp
- autobahn/wamp_session.ipp
- autobahn/wamp_websocket_transport.ipp
- autobahn/wamp_websocketpp_websocket_transport.ipp
Explicit use of boost::copy_exception to fix `error: call of overloaded 'copy_exception(...)' is ambiguous` error.
> Explicit use boost::copy_exception fixes #134

- autobahn/wamp_websocketpp_websocket_transport.hpp
The combination of "#pragma warning" and compiling with MinGW with "-Werror" makes this an error during compilation.
> disable #pragma warning for mingw

- examples/callee.cpp
Without this, this example hangs.
Re-using the same future hangs for me at 'registration.get()' with both msvc on Windows and gcc4.9 on Debian.
> add a seperate future for each provide

- CMakeLists.txt
Add boost_config.hpp to the list of public sources in CMakeLists.txt
so that it is included when using the `install` target generated by
CMake.
> add missing header to CMake install rules

- .gitignore
- autobahn/wamp_invocation.hpp
- autobahn/wamp_invocation.ipp
Exposed the details sent with the WAMP invocation so that they may be read by the client hosting the procedure.
They are stored in the wamp_invocation_impl as a msgpack object and exposed as a map, using the same access style as the methods that access the keyword arguments. The details member is set using the set_details method, which also sets the URI and progressive results flag.
> Expose details within wamp_invocation_impl

- autobahn/wamp_auth_utils.hpp
I had to fix this part of the code for OpenSSL 1.1.x (Debian testing/stretch). The changes are minor, and you might want to add an ifdef for older versions of OpenSSL -or not.
> fix compilation for OpenSSL 1.1.x

- autobahn/wamp_auth_utils.hpp
Added rules to conditionally use the compatible HMAC authentication code based on detected OpenSSL version.
While not strictly anything earth-shattering, a project I'm working on doesn't have anything newer than a (LTS support team) patched version of OpenSSL 1.0.1e. Therefore, updating to the latest Autobahn caused our build to break (ref: [#148](https://github.com/crossbario/autobahn-cpp/pull/148)). Therefore, I added the rules so that others that have the same issue with older versions of OpenSSL being the only ones available can still use the latest Autobahn out of the box.
I didn't test this on a machine that has OpenSSL >= 1.1 as I don't readily have access to one, so someone may want to do that to make sure these changes mesh. If not, I'll see what I can do to grab a few cycles and …
> Add preprocessor rules for OpenSSL < 1.1 compatibility

- autobahn/wamp_session.ipp
- autobahn/wamp_websocketpp_websocket_transport.hpp
- autobahn/wamp_websocketpp_websocket_transport.ipp
Websocket++ transport appeared to be still connected when it actually was not in some edge cases.
Fixed.
> Fixed transport connect state detection for WAMP websocket (websocketpp) transport

- autobahn/wamp_arguments.hpp
To replicate run
mkdir build
cd build
CXXFLAGS="-fsanitize=undefined -DMSGPACK_DEFAULT_API_VERSION=1" cmake ..
./examples/caller
You should see
/usr/include/msgpack/v1/object.hpp:636:15: runtime error: reference binding to null pointer of type 'struct zone'
/usr/include/msgpack/v1/object.hpp:636:15: runtime error: reference binding to null pointer of type 'struct zone'
Pass a default zone to the constructors.
> Fix undefined behaviour reported by gcc-7.3 sanitize=undefined

- cmake/Includes/CMakeLists.txt
See [cmake docs on BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) for details
Closes #188
> Statically link against boost if BUILD_SHARED_LIBS is dissabled

- autobahn/wamp_arguments.hpp
- autobahn/wamp_call.hpp
- autobahn/wamp_call_result.hpp
- autobahn/wamp_event.hpp
- autobahn/wamp_invocation.hpp
- autobahn/wamp_message.hpp
- autobahn/wamp_rawsocket_transport.hpp
- autobahn/wamp_rawsocket_transport.ipp
- autobahn/wamp_session.hpp
- autobahn/wamp_websocket_transport.ipp
See [note on MSGPACK_DISABLE_LEGACY_CONVERT](https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_configure#msgpack_disable_legacy_convert-since-140)
and [release note for version 2.0.0](https://github.com/msgpack/msgpack-c/releases/tag/cpp-2.0.0)
> Add support for current versions of msgpack-c

- autobahn/wamp_event.hpp
- autobahn/wamp_event.ipp
- autobahn/wamp_session.ipp
- examples/subscriber.cpp
Sometimes it might be desirable if instances of wamp_event could be copyable, for example when used in conjuction with other 3rd party libraries. The wamp_invocation type already supports this, so the pattern is reused for wamp_event aswell.
> Make wamp_event copyable

- autobahn/wamp_rawsocket_transport.ipp
- autobahn/wamp_session.ipp
This fixes the warning in C++20, and remains warning-free on older C++-versions by explicitly specifying all lambda captures. If you were only targeting C++20, you could use [=, this], but that's a warning in older versions. 😢 
`warning: implicit capture of 'this' via '[=]' is deprecated in C++20 [-Wdeprecated]`
> Fix warning re: implicit `this` lambda capture in C++20 

- .github/workflows/ci.yaml
It's mostly set up to support more OSes and compilers because I was originally going to add Clang right away, but it turns out that building boost with clang + libc++ is non-trivial. I can add it and MSVC in a later PR if you don't mind GitHub actions. :)
I use pip to install cmake since that's the most convenient way that works everywhere, and you get newer cmake faster than with apt.
Successful build here: https://github.com/robinlinden/autobahn-cpp/runs/1119335338?check_suite_focus=true
> Add CI using GitHub Actions

- examples/provide_prefix.cpp
Serializing arrays require providing a zone to msgpack for it to be
happy (sometimes).
My commit adding CI was based on a commit older than the one where I fixed the provide_prefix example not being compiled, so I didn't notice it was broken when I tested things.
I also can't reproduce the linker error locally, but it seems that msgpack always requires a zone when the type you serialize maps to a MAP or ARRAY, and on CI "prefix" mapped to char[7], so that's an array in msgpack, I suppose.
See: https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_object
The error:
```
/usr/bin/ld: CMakeFiles/provide_prefix.dir/provide_prefix.cpp.o: in function `msgpack::v2::object::object<char [7]>(char const (&) [7])':
/usr/include/msgpack/v2/object_fwd.hpp:36: undefined reference to `void …
```
> Fix link error in provide_prefix with some compilers

- autobahn/wamp_auth_utils.hpp
- autobahn/wamp_rawsocket_transport.ipp
- autobahn/wamp_session.ipp
Normally I'd just delete this since we explicitly copy it into the
lambda anyway, but there are a lot of comments here about that this may
be needed(?)
warning C4834: discarding return value of function with 'nodiscard'
attribute
> Fix VS2019 warning due to discarding nodiscard value

- .github/workflows/ci.yaml
- autobahn/wamp_websocketpp_websocket_transport.ipp
- cmake/Includes/CMakeLists.txt
- cmake/Modules/FindMsgpack.cmake
- cmake/Modules/FindWebsocketpp.cmake
- conanfile.txt
- examples/CMakeLists.txt
This is mainly in preparation of the Windows CI (and to make building and testing autobahn_cpp on systems without everything installed more convenient).
Usage:
```
mkdir -p build && cd build
conan install ..
cmake .. -DCMAKE_PREFIX_PATH=`pwd` -DCMAKE_MODULE_PATH=`pwd`
make -j
```
If you don't already have conan installed and set up, you can do so by doing
```
pip install conan
conan profile new default --detect
conan profile update settings.compiler.libcxx=libstdc++11 default
```
> Add support for installing dependencies using a conanfile

- .github/workflows/ci-linux.yaml
- .github/workflows/ci-windows.yaml
- examples/CMakeLists.txt
I added the Windows jobs in a separate workflow file as it differed too much from the Linux CI to make sense in there.
The new Boost_DEFINITIONS is because Boost has a weird autolink feature (probably something like `#pragma link boostlib.lib` behind a bunch of defines) that assumes that libraries are named in a specific way and that can be disabled by setting a define. Conan places this define in Boost_DEFINITIONS.
> Add Visual Studio x86 and AMD64 CI builds

- conanfile.py
- conanfile.txt
This enables the packaging as conan package and thus later distribution via conan-center etc.
This is the first part of #215
> Initial conanfile.py for possible distribution

- .github/workflows/ci-linux.yaml
- autobahn/wamp_session.ipp
Currently the start future is incorrectly signaled, probably cut'n'paste from the start method above.
> wamp_session: set_exception on the correct future
